apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: boardgame
  labels:
    app: boardgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      name: boardgame
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: ranaabhi02/boardabhi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  namespace: boardgame
spec:
  type: NodePort
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31100
